const imageSources = {
    "cartoon" : [
        {"src:" : "ben.png", "name": "ben10"},
        {"src:" : "doremon.jpg", "name": "doremon"},
        {"src:" : "duck.jpeg", "name": "duck"},
        {"src:" : "hattori.jpg", "name": "hattori"},    
        {"src:" : "jack.png", "name": "jack"},
        {"src:" : "jerry.png", "name": "jerry"},
        {"src:" : "oggy.jpeg", "name": "oggy"},
        {"src:" : "peter.png", "name": "peter"},
        {"src:" : "popeya.jpeg", "name": "popeya"},
        {"src:" : "scoobydoo.jpeg", "name": "scoobydoo"},
        {"src:" : "sinchan.jpg", "name": "sinchan"},
        {"src:" : "sisimaru.jpeg", "name": "sisimaru"},
        {"src:" : "sizuka.jpg", "name": "sizuka"},
        {"src:" : "spike.png", "name": "spike"},
        {"src:" : "tom.png", "name": "tom"},
    ],

    "animal" : [
        {"src:" : "bear.jpeg", "name": "bear"},
        {"src:" : "cat.jpg", "name": "cat"},
        {"src:" : "chimp.jpeg", "name": "chimp"},
        {"src:" : "cow.jpeg", "name": "cow"},    
        {"src:" : "dog.jpeg", "name": "dog"},
        {"src:" : "fox.jpeg", "name": "fox"},
        {"src:" : "hippo.jpeg", "name": "hippo"},
        {"src:" : "lion.jpeg", "name": "lion"},
        {"src:" : "panda.jpg", "name": "panda"},
        {"src:" : "rabbit.jpeg", "name": "rabbit"},
        {"src:" : "racoon.jpeg", "name": "racoon"},
        {"src:" : "rhino.jpeg", "name": "rhino"},
        {"src:" : "squirrel.jpeg", "name": "squirrel"},
        {"src:" : "tiger.jpeg", "name": "tiger"},
        {"src:" : "wolf.jpeg", "name": "wolf"},
    ],

    "car" : [
        {"src:" : "astonmartin.png", "name": "astonmartin"},
        {"src:" : "audi.jpg", "name": "audi"},
        {"src:" : "bmw.png", "name": "bmw"},
        {"src:" : "bugatti.jpg", "name": "bugatti"},    
        {"src:" : "ferrari.jpg", "name": "ferrari"},
        {"src:" : "hyundai.png", "name": "hyundai"},
        {"src:" : "jaguar.jpg", "name": "jaguar"},
        {"src:" : "koenigsegg.png", "name": "koenigsegg"},
        {"src:" : "lamborghini.jpg", "name": "lamborghini"},
        {"src:" : "landrover.jpeg", "name": "landrover"},
        {"src:" : "mahendra.jpg", "name": "mahendra"},
        {"src:" : "mclaren.jpeg", "name": "mclaren"},
        {"src:" : "mercedes.jpg", "name": "mercedes"},
        {"src:" : "porsche.png", "name": "porsche"},
        {"src:" : "rollsroyce.jpg", "name": "rollsroyce"},
        {"src:" : "tata.jpg", "name": "tata"},
        {"src:" : "toyota.jpg", "name": "toyota"},
        {"src:" : "volkswagen.jpg", "name": "volkswagen"},
    ]
}

export default imageSources