const imageSources = {
    "cartoon" : [
        {"src:" : "ben.jpeg", "name": "ben10"},
        {"src:" : "doremon.jpeg", "name": "doremon"},
        {"src:" : "bheem.jpeg", "name": "bheem"},
        {"src:" : "hattori.jpeg", "name": "hattori"},    
        {"src:" : "jack.jpeg", "name": "jack"},
        {"src:" : "jerry.jpeg", "name": "jerry"},
        {"src:" : "oggy.jpeg", "name": "oggy"},
        {"src:" : "peter.jpeg", "name": "peter"},
        {"src:" : "popeya.jpeg", "name": "popeya"},
        {"src:" : "scoobydoo.jpeg", "name": "scoobydoo"},
        {"src:" : "sinchan.jpeg", "name": "sinchan"},
        {"src:" : "spongebob.jpeg", "name": "spongebob"},
        {"src:" : "shizuka.jpeg", "name": "shizuka"},
        {"src:" : "kungfupanda.jpeg", "name": "kungfupanda"},
        {"src:" : "tom.jpeg", "name": "tom"},
    ],

    "animal" : [
        {"src:" : "bear.jpeg", "name": "bear"},
        {"src:" : "cat.jpeg", "name": "cat"},
        {"src:" : "chimp.jpeg", "name": "chimp"},
        {"src:" : "cow.jpeg", "name": "cow"},    
        {"src:" : "dog.jpeg", "name": "dog"},
        {"src:" : "fox.jpeg", "name": "fox"},
        {"src:" : "hippo.jpeg", "name": "hippo"},
        {"src:" : "lion.jpeg", "name": "lion"},
        {"src:" : "panda.jpeg", "name": "panda"},
        {"src:" : "rabbit.jpeg", "name": "rabbit"},
        {"src:" : "racoon.jpeg", "name": "racoon"},
        {"src:" : "rhino.jpeg", "name": "rhino"},
        {"src:" : "squirrel.jpeg", "name": "squirrel"},
        {"src:" : "tiger.jpeg", "name": "tiger"},
        {"src:" : "wolf.jpeg", "name": "wolf"},
    ],

    "car" : [
        {"src:" : "astonmartin.jpeg", "name": "astonmartin"},
        {"src:" : "audi.jpeg", "name": "audi"},
        {"src:" : "bmw.jpeg", "name": "bmw"},
        {"src:" : "bugatti.jpeg", "name": "bugatti"},    
        {"src:" : "ferrari.jpeg", "name": "ferrari"},
        {"src:" : "hyundai.jpeg", "name": "hyundai"},
        {"src:" : "jaguar.jpeg", "name": "jaguar"},
        {"src:" : "koenigsegg.jpeg", "name": "koenigsegg"},
        {"src:" : "lamborghini.jpeg", "name": "lamborghini"},
        {"src:" : "landrover.jpeg", "name": "landrover"},
        {"src:" : "mahendra.jpeg", "name": "mahendra"},
        {"src:" : "mclaren.jpeg", "name": "mclaren"},
        {"src:" : "mercedes.jpeg", "name": "mercedes"},
        {"src:" : "porsche.jpeg", "name": "porsche"},
        {"src:" : "rollsroyce.jpeg", "name": "rollsroyce"},
        {"src:" : "tata.jpeg", "name": "tata"},
        {"src:" : "toyota.jpeg", "name": "toyota"},
        {"src:" : "volkswagen.jpeg", "name": "volkswagen"},
    ]
}

export default imageSources